# SPDX-License-Identifier: PMPL-1.0-or-later
name: lint

permissions: read-all

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  markdown_and_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4

      - name: lint
        run: scripts/lint.bash

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.23
        with:
          args: -color
